config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions' }
  devise_for :admins, controllers: { registrations: 'admin/registrations', sessions: 'admin/sessions' }

  namespace :admin do
    resources :books do
      member do
        patch :publish
        patch :unpublish
      end
      # resources :orders, only: [ :index, :create]
    end
    resources :orders, only: [:index, :update] do
      member do
        patch :accepted
        patch :rejected
      end
      collection do
        get :pending_orders
      end
    end
    resources :users, only: [:index]
  end

  namespace :user do
    resources :books, only: [:index,:show] do
      collection do
        get :inventory
      end
      resources :orders, only: [:create]
    end
  end

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book <  ApplicationRecord
  has_one_attached :picture

  belongs_to :admin
  has_many :orders, dependent: :destroy
  has_many :users, through: :orders

  def self.published
    where(published: true)
  end
end

app/models/order.rb
class Order <  ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum status: [:pending, :approved, :rejected]

  # def self.approved
  #   where(status: 'approved')
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :books, -> { where(orders: { status: :approved }) }, through: :orders
  def name
    "#{first_name} #{last_name}"
  end

  def book_ordered?(book_id)
    order_book_ids.include?(book_id)
  end

  def order_book_ids
    orders.pluck(:book_id)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_admin.books.create(permitted_params)
    if @book.present?
      flash[:notice] = "Book created successfully."
      redirect_to admin_book_path(@book)
    else
      flash[:notice] = "Error"
      redirect_to new_admin_book_path
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(permitted_params)
    flash[:notice] = "Book Updated successfully."
    redirect_to admin_book_path(@book)
  end

  def publish
    @book = Book.find(params[:id])
    @book.update_attribute(:published, true)
    flash[:notice] = "Book published successfully."
    redirect_to admin_book_path(@book)
  end

  def unpublish
    @book = Book.find(params[:id])
    @book.update_attribute(:published, false)
    flash[:notice] = "Book unpublished successfully."
    redirect_to admin_book_path(@book)
  end

  def destroy
    @book = Book.destroy(params[:id])
    flash[:notice] = "Book deleted succesfully " if @book.destroy
    redirect_to admin_books_path
  end
  private

  def permitted_params
    params.require(:book).permit(:title, :author, :amount, :description, :picture, :published)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def pending_orders
    @pending_orders = Order.pending
  end

  def accepted
    @order = Order.find(params[:id])
    @order.update(status: :approved)
    flash[:notice] = 'Order accepted '
    redirect_to pending_orders_admin_orders_path
  end

  def rejected
    @order = Order.find(params[:id])
    @order.update(status: :rejected)
    flash[:notice] = 'Order rejected '
    redirect_to pending_orders_admin_orders_path
  end
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    user_books_path
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  private

  def after_sign_in_path_for(admin)
    admin_books_path
  end
end

app/controllers/admin/users_controller.rb
class  Admin::UsersController < AdminController
  def index
    @users = User.all
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

    #   def after_sign_in_path_for(user)
    #   admin_index_path(current_user)

  protected

  def configure_permitted_parameters
    attributes = [:first_name, :last_name, :email] if resource_name == :admin
    attributes = [:first_name, :last_name, :email] if resource_name == :user
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user/books_controller.rb
class User::BooksController < UserController

  def index
    @books = Book.published
  end

  def show
    @book = Book.find(params[:id])
  end

  def inventory
    @orders = current_user.orders.approved
    @pending_orders = current_user.orders.pending
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < UserController
  before_action :set_book
  def create
    order = current_user.orders.create(book: @book)
    if order.present?
      flash[:notice] = "Order created sucessfully"
      redirect_to user_books_path
    else
    end

    # def show
    # # @books = Book.find(params[:id])
    # end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    user_books_path
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
 private

  def after_sign_in_path_for(user)
    user_books_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/user_controller.rb
class UserController < ApplicationController
  # before_action :authenticate_user!

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/books/edit.html.erb
<div class= " container">
  <div class="d-flex justify-content-between align-items-center">
    <h2>Edit Books</h2>
   </div>
</div>


<div class="col-lg-5 col-md-7 col-sm-11 mx-auto" >

<%= form_with model: [:admin, @book] do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'form-label' %><br />
    <%= f.text_field :title, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :author, class: 'form-label' %><br />
    <%= f.text_field :author, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :amount, class: 'form-label' %><br />
    <%= f.number_field :amount, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'form-label' %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :picture, class: 'form-label' %><br />
    <%= f.file_field :picture, autofocus: true, :required => @book.new_record? %>
  </div>

  <div class="actions">
    <%= f.submit "Update", class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/admin/books/index.html.erb
<div class = "container">
  <h3 >Welcome <%= current_admin.first_name %> to admin dashboard </h3>
  <br>
  <div class="d-flex justify-content-between">
    <h3>Books</h3>
  </div>
  <% @books.each do |book| %>
    <div class= "mt-4 card">
      <div class= "card-body">
        <div class = "d-flex justify-content-between">
          <div>
            <h5 class="card-title"><%= book.title %></h5>
            <%= link_to 'Show', admin_book_path(book), class: 'btn btn-primary' %>
            <%= link_to 'Edit', edit_admin_book_path(book), class: 'btn btn-info' %>
            <%= link_to 'Delete', admin_book_path(book), method: :delete, data: {confirm: "Are you sure "}, class: 'btn btn-danger' %>
          </div>
          <div>
            <% if book.published? %>
            <%= link_to "Published",admin_book_path(book), class: 'btn btn-light' %>
            <% else %>
            <%= link_to "Not Published", admin_book_path(book), class: 'btn btn-light' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/books/new.html.erb
<div class= " container">
  <div class="d-flex justify-content-between align-items-center">
    <h2>Create Books</h2>
   </div>
</div>


<div class="col-lg-5 col-md-7 col-sm-11 mx-auto" >

<%= form_with model: [:admin, @book] do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'form-label' %><br />
    <%= f.text_field :title, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :author, class: 'form-label' %><br />
    <%= f.text_field :author, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :amount, class: 'form-label' %><br />
    <%= f.number_field :amount, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'form-label' %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "email",  class: 'form-control', :required => true %>
  </div>

  <div class="form-group">
    <%= f.label :picture, class: 'form-label' %><br />
    <%= f.file_field :picture, autofocus: true, :required => @book.new_record? %>
  </div>

  <div class="actions">
    <%= f.submit "Create", class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/admin/books/show.html.erb
<h1>New book </h1>
<div class="container">
<% if @book.published? %>
  <%= link_to "Unpublish", unpublish_admin_book_path(@book), method: :patch, class: 'btn btn-primary' %>
<% else %>
  <%= link_to "Publish", publish_admin_book_path(@book), method: :patch, class: 'btn btn-primary' %>
<% end %>
<h1>Title : <%= @book.title %></h1>
<h5>Author : <%= @book.author%></h5>
<p>Description : <%= @book.description%></p>
 Amount : <%= @book.amount%><br>
 Image : <%= image_tag(@book.picture, style: "width:100%" )%>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
      <h2>List of all orders</h2>
    <div class="d-flex align-items-center">
      <%= link_to 'Pending Orders',pending_orders_admin_orders_path , class: 'btn btn-primary'  %>
    </div>
  </div>
  <table class="table">
   <thead>
    <tr>
      <th>Buyer</th>
      <th>Book</th>
      <th>Price</th>
      <th>Status</th>
    </tr>
   </thead>
   <tbody>
   <% @orders.each do |order| %>
    <tr>
      <td> <%= order.user.first_name %></td>
      <td><%= order.book.title %></td>
      <td><%= order.book.amount %></td>
      <td><%= order.status%></td>
    </tr>
   <% end %>
  </tbody>
  </table>
</div>

app/views/admin/orders/pending_orders.html.erb
<div class="container">
  <h2>List of all pending orders</h2>
  <table class="table">
   <thead>
    <tr>
      <th>Buyer</th>
      <th>Book</th>
      <th>Price</th>
      <th>Accept</th>
      <th>Reject</th>

    </tr>
   </thead>
   <tbody>
      <% @pending_orders.each do |pending_order| %>
      <tr>
        <td><%= pending_order.user.first_name %></td>
        <td><%= pending_order.book.title %></td>
        <td><%= pending_order.book.amount %></td>
        <td><%= link_to "Accept",  accepted_admin_order_path(pending_order), method: :patch, class: "btn btn-info " %></td>
        <td><%= link_to "Reject",  rejected_admin_order_path(pending_order),method: :patch, class: "btn btn-danger "%></td>
      </tr>
      <% end %>
  </tbody>
  </table>
</div>

app/views/admin/users/index.html.erb
<div class="container">
<h1>All Users</h1>
  <table class="table">
   <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Owned books</th>
    </tr>
   </thead>
   <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.orders.approved.count %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div class= "container">
  <h1>Welcome to Books World</h1>
  <div class="aa">
    <button type="button" class="btn btn-light mb-5"><a href="admins/sign_in">Login as a Admin </a></button> <br>
    <button type="button" class="btn btn-light mt-5"><a href="users/sign_in">Login as a User</a></button>
  </div>
</div>

app/views/user/books/index.html.erb
<div class="container">
<h1>Welcome to Book-Store</h1>
  <div class="d-flex justify-content-between align-items-center">
    <h2>Books</h2>
  </div>

  <table class="table">
   <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Price</th>
      <th>View</th>
    </tr>
   </thead>
   <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.amount %></td>
      <td><%= link_to 'View',  user_book_path(book) %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/user/books/inventory.html.erb
<div class="container">
  <h1>My Collection</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Discription</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
      <tr>
        <td><%= order.book.title %></td>
        <td><%= order.book.author %></td>
        <td><%= order.book.description %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="container">
  <div class= "mt-5">
  <h4>Other Pending orders</h4>
  <table class="table">
  <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>amount</th>
        <th>status</th>
      </tr>
  </thead>
  <tbody>
  <tr>
  <% @pending_orders.each do |pending_order| %>
    <td><%= pending_order.book.title %></td>
    <td><%= pending_order.book.author %></td>
    <td><%= pending_order.book.amount %></td>
    <td><%= pending_order.status %></td>
  </tr>
  <% end %>
  </tbody>
 </table>
 </div>
</div>

app/views/user/books/show.html.erb
<div class="container">
  <div class="d-flex justify-content-end">
    <%= link_to 'Place order', user_book_orders_path(@book), method: :post, class: "btn btn-primary" unless current_user.book_ordered?(@book.id) %>
  </div>
  <div>
    <h5>Title : <%= @book.title %></h4>
    <h5>Author : <%= @book.author%></h5>
    <h5>Amount : <%= @book.amount%></h5>
    <h5>Description</h5>  <%= @book.description%></p>
  </div>
  <h5>Image</h5> <%= image_tag(@book.picture, style: "width:100%" )%>
</div>