config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: 'user/registrations', sessions: 'user/sessions' }
  devise_for :admins, controllers: { registrations: 'admin/registrations', sessions: 'admin/sessions' }

  namespace :admin do
    resources :books do
      member do
        patch :publish
        patch :unpublish
      end
      # resources :orders, only: [ :index, :create]
    end
    resources :orders, only: [:index, :update] do
      member do
        patch :accepted
        patch :rejected
      end
      collection do
        get :pending_orders
      end
    end
    resources :users, only: [:index]
  end

  namespace :user do
    resources :books, only: [:index,:show] do
      collection do
        get :inventory
      end
      resources :orders, only: [:create]
    end
  end

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book <  ApplicationRecord
  has_one_attached :picture

  belongs_to :admin
  has_many :orders, dependent: :destroy
  has_many :users, through: :orders

  def self.published
    where(published: true)
  end
end

app/models/order.rb
class Order <  ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum status: [:pending, :approved, :rejected]

  # def self.approved
  #   where(status: 'approved')
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :books, -> { where(orders: { status: :approved }) }, through: :orders
  def name
    "#{first_name} #{last_name}"
  end

  def book_ordered?(book_id)
    order_book_ids.include?(book_id)
  end

  def order_book_ids
    orders.pluck(:book_id)
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_admin.books.create(permitted_params)
    if @book.present?
      flash[:notice] = "Book created successfully."
      redirect_to admin_book_path(@book)
    else
      flash[:notice] = "Error"
      redirect_to new_admin_book_path
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(permitted_params)
    flash[:notice] = "Book Updated successfully."
    redirect_to admin_book_path(@book)
  end

  def publish
    @book = Book.find(params[:id])
    @book.update_attribute(:published, true)
    flash[:notice] = "Book published successfully."
    redirect_to admin_book_path(@book)
  end

  def unpublish
    @book = Book.find(params[:id])
    @book.update_attribute(:published, false)
    flash[:notice] = "Book unpublished successfully."
    redirect_to admin_book_path(@book)
  end

  def destroy
    @book = Book.destroy(params[:id])
    flash[:notice] = "Book deleted succesfully " if @book.destroy
    redirect_to admin_books_path
  end
  private

  def permitted_params
    params.require(:book).permit(:title, :author, :amount, :description, :picture, :published)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def pending_orders
    @pending_orders = Order.pending
  end

  def accepted
    @order = Order.find(params[:id])
    @order.update(status: :approved)
    flash[:notice] = 'Order accepted '
    redirect_to pending_orders_admin_orders_path
  end

  def rejected
    @order = Order.find(params[:id])
    @order.update(status: :rejected)
    flash[:notice] = 'Order rejected '
    redirect_to pending_orders_admin_orders_path
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  private

  def after_sign_in_path_for(admin)
    admin_books_path
  end
end

app/controllers/admin/users_controller.rb
class  Admin::UsersController < AdminController
  def index
    @users = User.all
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

    #   def after_sign_in_path_for(user)
    #   admin_index_path(current_user)

  protected

  def configure_permitted_parameters
    attributes = [:first_name, :last_name, :email] if resource_name == :admin
    attributes = [:first_name, :last_name, :email] if resource_name == :user
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user/books_controller.rb
class User::BooksController < UserController

  def index
    @books = Book.published
  end

  def show
    @book = Book.find(params[:id])
  end

  def inventory
    @orders = current_user.orders.approved
    @pending_orders = current_user.orders.pending
  end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < UserController
  before_action :set_book
  def create
    order = current_user.orders.create(book: @book)
    if order.present?
      flash[:notice] = "Order created sucessfully"
      redirect_to user_books_path
    else
    end

    # def show
    # # @books = Book.find(params[:id])
    # end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    user_books_path
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
 private

  def after_sign_in_path_for(user)
    user_books_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/user_controller.rb
class UserController < ApplicationController
  # before_action :authenticate_user!

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">      

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render "shared/navbar"  %>

  <div class="container">

    <% flash.each do |key, value|%>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= value %>
      </div>
    <% end %>

  </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-dark mb-5'>
  <h3>
    <% if admin_signed_in? %>
      <%= link_to 'Book Store', admin_books_path, class: 'navbar-brand' %>
    <% elsif %>
      <%= link_to 'Book Store', user_books_path, class: 'navbar-brand' %>
    <% end %>
  </h3>
  </button>
    <ul class='navbar-nav mr-auto'>
      <li class='nav-item active'></li>
      <li class='nav-item'></li>
      <li class='nav-item'></li>
    </ul>
    <span class='navbar-text'>
      <% if admin_signed_in? %>
        <%= link_to 'Create Book', new_admin_book_path, class: 'btn btn-outline-secondary'  %>
        <%= link_to 'Orders',  admin_orders_path, class: 'btn btn-outline-secondary'  %>
        <%= link_to 'All Users',  admin_users_path, class: 'btn btn-outline-secondary'  %>
        <%= link_to 'Signout', destroy_admin_session_path, method: :delete, class: 'btn btn-primary' %>
      <% elsif user_signed_in? %>
        <%= link_to 'My collection', inventory_user_books_path, class: "btn btn-outline-secondary" %>
        <%= link_to 'Signout', destroy_user_session_path, method: :delete,  class: "btn btn-primary" %>
      <% end %>
    </span>
  </div>
</nav>